import { Geist, Geist_Mono } from "next/font/google";
import Nav from "./components/Nav";
import { ArrayProvider } from "./context/ArrayContext.jsx";
import { PasswordProvider } from "./context/Password.jsx";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav />
        <main className="w-full h-screen">
          <ArrayProvider>
            <PasswordProvider>{children}</PasswordProvider>
          </ArrayProvider>
        </main>
      </body>
    </html>
  );
}
